## CSCI-467 Discussion (Week 1)

### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you some basic APIs of numpy, pandas and scikit-learn. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, Pandas, Numpy and Scikit-Learn in order to finish your programming assignments successfully.**
8. Have fun!

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

### Pandas

#### The read_csv() Method

First, read the documentation about the *read_csv()* method in Pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Then, try to read data from file Salaries.csv to a dataframe, make the column playerID in the csv file as the index column and the first row as the header. Also, skip the second row when reading the file.

In [12]:
import pandas as pd
pd.read_csv('Salaries.csv', index_col='playerID', skiprows=[2])

yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
chambch01    1985    ATL   NL    800000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25574 rows x 4 columns]

#### Indexing and Selecting Data

Select the id of the players who are registered in ATL and HOU and whose salary is higher than one million.

In [10]:
import pandas as pd
data = pd.read_csv('Salaries.csv', index_col='playerID')
greater_than_1_mil = data[((data.teamID=='ATL') | (data.teamID=='HOU')) & (data.salary>=1000000)]
print('Numer of players with ALT or HOU having salary greater than 1,000,000: ', greater_than_1_mil.shape[0])
print(greater_than_1_mil)

Numer of players with ALT or HOU having salary greater than 1,000,000:  625
           yearID teamID lgID   salary
playerID                              
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
ryanno01     1985    HOU   NL  1350000
hornebo01    1986    ATL   NL  1800000
...           ...    ...  ...      ...
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
thatcjo01    2015    HOU   AL  1000000
valbulu01    2015    HOU   AL  4200000

[625 rows x 4 columns]


#### The describe() Method

Calculate the standard Deviation, first quartile, medium, third quartile, mean, maximum, minimum of the salary in team ATL.

In [15]:
import pandas as pd
data = pd.read_csv('Salaries.csv', index_col='playerID')
data_ATL = data[(data.teamID=='ATL')]
data_ATL_std = data_ATL.std(axis=0)
print('Standard Deviation of team ATL salary is : ', data_ATL_std.salary)
data_ATL_mean = data_ATL.mean(axis=0)
print('Mean of team ATL salary is : ', data_ATL_mean.salary)
data_ATL_max = data_ATL.max(axis=0)
print('Max of team ATL salary is : ', data_ATL_max.salary)
data_ATL_quartile = data_ATL.quantile([0.25, 0.75, 0.5])
print('First and Third Quartiles, medium of team ATL salary is : ', data_ATL_quartile.salary)
data.describe()

Standard Deviation of team ATL salary is :  3432672.9832373876
Mean of team ATL salary is :  2206239.316027088
Max of team ATL salary is :  16061802
First and Third Quartiles, medium of team ATL salary is :  0.25     300000.0
0.75    2390625.0
0.50     600000.0
Name: salary, dtype: float64


yearID        salary
count  25575.000000  2.557500e+04
mean    2000.374389  2.008563e+06
std        8.610604  3.315706e+06
min     1985.000000  0.000000e+00
25%     1993.000000  2.750000e+05
50%     2000.000000  5.500000e+05
75%     2008.000000  2.250000e+06
max     2015.000000  3.300000e+07

#### The iterrows() Method

Create a Python dictionary object whose keys are the headers of the dataframe created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows method to iterate each row of the dataframe and copy it to a dictionary. However, there is a easier way. Learn how the to_dict() method works by yourself later)

In [16]:
import pandas as pd
data = pd.read_csv('Salaries.csv')
result = data.to_dict(orient='records')
print(result)

[{'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'barkele01', 'salary': 870000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'bedrost01', 'salary': 550000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'benedbr01', 'salary': 545000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'campri01', 'salary': 633333}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'ceronri01', 'salary': 625000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'chambch01', 'salary': 800000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'dedmoje01', 'salary': 150000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'forstte01', 'salary': 483333}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'garbege01', 'salary': 772000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'harpete01', 'salary': 250000}, {'yearID': 1985, 'teamID': 'ATL', 'lgID': 'NL', 'playerID': 'hornebo01', 'salary

#### Create Dataframe Using the Constructor

Read the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame and create a dataframe using pd.DataFrame from the dictionary created in the iterrows() exercise. Change the header to "a", "b", "c", ... at creation time.

In [18]:
df = pd.DataFrame(result)
df.columns = ['a', 'b', 'c', 'd', 'e']
print(df)

          a    b   c          d         e
0      1985  ATL  NL  barkele01    870000
1      1985  ATL  NL  bedrost01    550000
2      1985  ATL  NL  benedbr01    545000
3      1985  ATL  NL   campri01    633333
4      1985  ATL  NL  ceronri01    625000
...     ...  ...  ..        ...       ...
25570  2015  WAS  NL  treinbl01    512800
25571  2015  WAS  NL  ugglada01    507500
25572  2015  WAS  NL  werthja01  21000000
25573  2015  WAS  NL  zimmejo02  16500000
25574  2015  WAS  NL  zimmery01  14000000

[25575 rows x 5 columns]


### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

In [5]:
import numpy as np
arr = [[1, 2], [3, 4]]
np.array(arr)

array([[1, 2],
       [3, 4]])

#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

In [14]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print("Shape is :", arr.shape)
print("NDim is :", arr.ndim)
print("Size is : ", arr.size)
print("Dtype is :", arr.dtype)
print("Itemsize is :", arr.itemsize)
print("Data is : ", arr.data)

Shape is : (2, 2)
NDim is : 2
Size is :  4
Dtype is : int64
Itemsize is : 8
Data is :  <memory at 0x10c997050>


#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Flattened array: ", arr.flatten())
print("Reshaped array 3x2: ", arr.reshape(3,2))
print("Reshaped array 1x6: ", arr.reshape(1,6))

Flattened array:  [1 2 3 4 5 6]
Reshaped array 3x2:  [[1 2]
 [3 4]
 [5 6]]
Reshaped array 1x6:  [[1 2 3 4 5 6]]


#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

In [35]:
arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
print("Array excluding first row : ", arr[1:])
print("Array's last row : ", arr[-1])
print("Array excluding last row : ", arr[:-1])
print("Array excluding first element in each row : ", arr[:, 1:])
print("Array's first row, first element : ", arr[0, 0])
print("Array excluding last row, only including first two elements in each row : ", arr[:-1, 0:2])

Array excluding first row :  [[3 4 6]
 [7 8 9]]
Array's last row :  [7 8 9]
Array excluding last row :  [[1 2 3]
 [3 4 6]]
Array excluding first element in each row :  [[2 3]
 [4 6]
 [8 9]]
Array's first row, first element :  1
Array excluding last row, only including first two elements in each row :  [[1 2]
 [3 4]]


#### The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

In [42]:
import numpy as np
arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
arr2 = np.array([[1, 2, 1], [2, 1, 2], [1, 2, 1]])
print("argmin : ", np.argmin(arr))
print("argmax : ", np.argmax(arr))
print("min : ", np.min(arr))
print("max : ", np.max(arr))
print("mean : ", np.mean(arr))
print("sum : ", np.sum(arr))
print("std : ", np.std(arr))
print("dot : ", np.dot(arr, arr2))
print("square : ", np.square(arr))
print("sqrt : ", np.sqrt(arr))
print("abs : ", np.abs(arr))
print("exp : ", np.exp(arr))
print("sign : ", np.sign(arr))
print("mod : ", np.mod(arr, 2))

argmin :  0
argmax :  8
min :  1
max :  9
mean :  4.777777777777778
sum :  43
std :  2.657391276244755
dot :  [[ 8 10  8]
 [17 22 17]
 [32 40 32]]
square :  [[ 1  4  9]
 [ 9 16 36]
 [49 64 81]]
sqrt :  [[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.44948974]
 [2.64575131 2.82842712 3.        ]]
abs :  [[1 2 3]
 [3 4 6]
 [7 8 9]]
exp :  [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [2.00855369e+01 5.45981500e+01 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
sign :  [[1 1 1]
 [1 1 1]
 [1 1 1]]
mod :  [[1 0 1]
 [1 0 0]
 [1 0 1]]


#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [62]:
print("eye : ", np.eye(3))
print("ones : ", np.ones(5))
print("zeros : ", np.zeros(3))
print("linspace : ", np.linspace(2, 5))
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
print("concatenate : ", np.concatenate((a,b), axis=0))
print("arange : ", np.arange(10))

eye :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
ones :  [1. 1. 1. 1. 1.]
zeros :  [0. 0. 0.]
linspace :  [2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]
concatenate :  [[1 2]
 [3 4]
 [5 6]]
arange :  [0 1 2 3 4 5 6 7 8 9]


### Scikit-Learn

The followings are packages (or methods) in Python (Scikit-Learn and Scipy) that will be frequently used in your programming assignment. So, please read carefully.

- Data Preprocessing (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing)
    - Standardization: StandardScaler
    - Normalization: MinMaxScaler
    - Quantifing Categorical Features: LabelEncoder. OneHotEncoder
    - Construct Train and Test Set: model_selection.train_test_split
- KNN: KNeighborsClassifier
- Linear Regression: LinearRegression
- Logistic Regression: LogisticRegression, LogisticRegressionCV
- Feature Selection / Model Selection
    - L1 Penalized Regression (Lasso Regression) with Cross-Validation: LassoCV
    - L2 Penalized Regression (Ridge Regression) with Cross-Validation: RidgeCV
    - Cross-Validation: StratifiedKFold, RepeatedKFold, LeaveOneOut, KFold, model_selection.cross_validate, model_selection.cross_val_predict, model_selection.cross_val_score
    - Model Metrics (https://scikit-learn.org/stable/modules/classes.html#sklearn-metrics-metrics): accuracy_score, auc, f1_score, hamming_loss, precision_score, recall_score, roc_auc_score
- Decision Tree: DecisionTreeClassifier, DecisionTreeRegressor
- Bootstrap, Ensemble Methods
    - Bootstrap: bootstrapped (https://pypi.org/project/bootstrapped/)
    - Bagging: RandomForestClassifier, RandomForestRegressor
    - Boosting: AdaBoostClassifier, AdaBoostRegressor
- Support Vector Machines (https://scikit-learn.org/stable/modules/svm.html#svm): LinearSVC, LinearSVR
- Multiclass and Multilabel Classification (https://scikit-learn.org/stable/modules/classes.html#module-sklearn.multiclass)
    - One-vs-one Multiclass Strategy: OneVsOneClassifier
    - One-vs-the-rest (OvR) multiclass/multilabel strategy / OneVsRestClassifier
- Unsupervised Learning
    - K-means Clustering: KMeans
    - Hierarchical Clustering: scipy.cluster.hierarchy (not scikit-learn)
- Semisupervised Learning (https://scikit-learn.org/stable/modules/label_propagation.html)

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.